version: '3.3'
services:
  db:
    image: postgres:15.0
    restart: unless-stopped 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  web:
    image: sebivenlo/prj1-web:1.0
    restart: unless-stopped 
    user: ${UID}:${GID}
    ports:
      - '127.0.0.1:${WEB_PORT}:80'
    volumes:
      - '${WEB_VOLUME}:/var/www/html'
    depends_on:
      - db
volumes:
  prj1_db:
    driver: local
  prj1_web:
    driver: local